version: "2"

services:
  app:
    build: .
    command: nodemon demo/demo.js
    environment:
        NODE_ENV: dev
    ports:
        - '9091:9091'
    volumes:
        - .:/usr/src/app/
        - /usr/src/app/node_modules
